### ISSUE TITLE
Can't scroll in console while scan is running

### ISSUE THREAD

**Issue by ajurgenson55** [sonatype-nexus-community/auditjs#100]
I think the spinner might be refreshing and overwriting the last line of console output

This means it resets the scroll bar of the terminal to the new line even though it appears like its not changing, snapping back any scroll bar movement making it impossible

**Comment by DarthHater** [comment]
This is indeed what is happening. What does this prevent?

**Comment by ajurgenson55** [comment]
Prevents you from looking at previous terminal output while a scan is going, doesn't affect functionality just usability of the terminal

**Comment by allenhsieh** [comment]
I've done some digging through Ora documentation and looked at other spinners -- This is expected behavior more or less. Should we close this issue or would you want to yank the spinner for a more static visual indicator?

**Comment by ajurgenson55** [comment]
Yeah this would be more work to figure out an alternative than it's worth, closing it out
