### ISSUE TITLE
Alpo Time - use auditjs to scan auditjs during CI

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/auditjs#101]
Update the CI config of the auditjs project to run auditjs against itself and report any vulnerabilities found. CI should fail if vulnerabilities are found.

Yummy dog food.

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
GO FOR IT! This is definitely something we want to do!

**Comment by ajurgenson55** [comment]
Well all the dependencies are there already so it should be light, I guess that means the previous release scans the next release.

Wondering if config for circle ci can be persistent in the SaaS version
