### ISSUE TITLE
Console output hanging on polling when tested against https URL

### ISSUE THREAD

**Issue by ajurgenson55** [sonatype-nexus-community/auditjs#103]
Decided to test against BMA environments to make sure auditjs-iq functions against a separate https iq server endpoint

It looks like it is hanging on the polling and not getting confirmation back from the IQ Server that the scan is done

`ajurgenson@ArtieSonaDell:~/test-apps/Angular-JumpStart$ auditjs iq -a auditjs-uat -s build

✔ Starting application
✔ Getting coordinates for Nexus IQ Server
✔ Auditing your application with Nexus IQ Server
✔ Getting your internal application ID
✔ Submitting your dependencies to Nexus IQ Server
⠴ Checking for results (this could take a minute)`

That's where it's hanging indefinitely, but the report is available in IQ Server pretty quickly.  

Will test against internal IPs through the vpn to see if this is an https issue or something else

**Comment by ajurgenson55** [comment]
Looks like it's not related to http vs https but also getting the same issue from an http internal IP on an AWS ec2 instance with the same behavior.  

```
  '1': 'bc6162b7445141d6b91e8589457e5bc7',
  level: 'debug',
  message: 'Submitting sbom to Nexus IQ Server third party API',
  label: 'AuditJS',
  timestamp: '2020-01-13T20:02:30.912Z' }
✔ Submitting your dependencies to Nexus IQ Server
⠋ Checking for results (this could take a minute){ '0':
   'api/v2/scan/applications/bc6162b7445141d6b91e8589457e5bc7/status/54eb4cab36464ab8a14d552ca446edfd',
  level: 'debug',
  message: 'Polling Nexus IQ Server for report results',
  label: 'AuditJS',
  timestamp: '2020-01-13T20:02:31.027Z' }
⠹ Checking for results (this could take a minute)
ajurgenson@ArtieSonaDell:~/test-apps/Angular-JumpStart$ auditjs iq -a auditjs-uat -s build --verbose
```

Looks like we don't have debug output in polling function of the request service itself, only right before the initial polling call.  Will work on getting the actual API call and testing it manually to see what's going on

**Comment by ajurgenson55** [comment]
```
✔ Submitting your dependencies to Nexus IQ Server
⠋ Checking for results (this could take a minute){ '0': 'http://localhost:8070',
  level: 'debug',
  message: 'Server URL for polling: ',
  label: 'AuditJS',
  timestamp: '2020-01-13T20:27:18.330Z' }
{ '0':
   'api/v2/scan/applications/bc6162b7445141d6b91e8589457e5bc7/status/8182a6b96d0048438c5b4867963d03ef',
  level: 'debug',
  message: 'Polling Nexus IQ Server for report results',
  label: 'AuditJS',
  timestamp: '2020-01-13T20:27:18.331Z' }
⠋ Checking for results (this could take a minute)^C
ajurgenson@ArtieSonaDell:~/git_repos/auditjs$
```

Added the logging for the args.server param that gets passed into polling and it looks like it still uses the default localhost url for polling which would explain why its hanging.  Should be a quick fix to pass the configured server url into the polling section

**Comment by ajurgenson55** [comment]
Works with the server url explicitly specified so it looks like the issue is that it's not picking up the config in the file for the polling

**Comment by allenhsieh** [comment]
Resolved in https://github.com/sonatype-nexus-community/auditjs/commit/e31ee2ac507c0bf97d31d7263610ff8a9ded2d66
