### ISSUE TITLE
Allow someone to specify which dependencies they want to scan

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/auditjs#114]
This is likely something we won't implement, since we are now using `read-installed` which scans whatever you have installed, and we have provided an option to not scan `devDependencies` which `read-installed` gave us. It is more likely we should update the README to reflect reality and inform users that if they want those scanned, they should install them!

**Comment by ajurgenson55** [comment]
Yeah, since we do it based on what's installed i think that is the most accurate portrayal.  If they want to scan other dependency categories just install them and run the scans.
