### ISSUE TITLE
Suppress Error Exit Code

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/auditjs#117]
This I do not believe we need to implement as you can do this easily with bash (and I'm assuming with Windows as well):

`auditjs ossi || true`

That should suppress any exit code other than 0 and coerce it into a 0 exit code.

I do not want to implement this as it could create some hairy code situations, and I like the idea that someone has to be a bit more explicit about ignoring it, rather than potentially forgetting they set a flag to.

**Comment by ajurgenson55** [comment]
I'm gonna say nah on this one, not worth the implementation effort when linux does it
