### ISSUE TITLE
Allow for someone to specify a different cache directory for AuditJS

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/auditjs#118]
This I do not THINK we need to implement but it may be that we do. I could potentially see a use case of setting it to `/tmp` or some other directory in systems where the user does not have a lot of access (mostly for CI/CD potentially)?

Would love to hear others feedback on this!

**Comment by ButterB0wl** [comment]
This could be a line when you set the OSSI config and just added to the config file

There is no way to persist a change to the location of the entire config directory unless you do something stupid like leave a pointer to the new directory in the ~ directory, so as long as we're only changing the cache directory here that should be pretty simple to do

**Comment by allenhsieh** [comment]
in #146
