### ISSUE TITLE
Investigate whether read-installed would be a better solution for scanning yarn projects

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/auditjs#125]
Right now for yarn we iterate the `yarn.lock` file and get our package list from in there. This has a drawback currently that it is looking at EVERY dependency, and `read-installed` has the ability to let us only look at the ones that we choose (you can exclude dev deps for example). As well, an SBOM may or may not be created in the same fashion for `yarn` so we could end up with inconsistent results between OSSI and IQ scans.

**Comment by ajurgenson55** [comment]
The cyclonedx bom works using read-installed for yarn projects using IQ yeah?  Why did we originally iterate through the yarn.lock, was the read-installed ossi implementation not working at first?

**Comment by DarthHater** [comment]
I am PRETTY sure we stole the yarn impl from 3.x and moved on. Then we found read-installed, and got it working for npm. You are correct that read-installed would be called for yarn, making it disjointed at the moment. So the options are: write an SBOM thing that uses the output of how we currently get yarn results, or switch our yarn implementation to use read-installed as well (making it virtually identical to our npmls impl).

**Comment by DarthHater** [comment]
Ok so taking a look, yarn currently looks consistent despite using a slightly different approach, we saw this specifically with @hboutemy as we looked at #132 , not voting to close this quite yet but feeling a bit better as his (and my) results were consistent.

**Comment by DarthHater** [comment]
I went ahead in #136 and got rid of any yarn specific code, as testing this seems to have worked.
