### ISSUE TITLE
Determine if we need to implement npm shrinkwrap functionality

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/auditjs#126]
Since `npm shrinkwrap` is kinda old at this time, do we really need to implement this? It would appear we do not, but let's make sure, as we could do some special handling for this case.

**Comment by ajurgenson55** [comment]
So as far as I can tell, shrinkwrap isn't going to affect what is in the node_modules folder which is what we are going through anyway.  It replaces the package-lock.json but since we're checking based on node_modules i think we're good here.

**Comment by DarthHater** [comment]
Good to hear @ajurgenson55 , that was my thought but I wanted a second opinion. I'll leave this open for a bit in case anyone chimes in with some more info.

**Comment by ButterB0wl** [comment]
closing out, can reopen as a bug if it becomes an issue through usage
