### ISSUE TITLE
Whitelist by command line for vulnerabilities

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/auditjs#128]
We already provide the ability to use a file for whitelisting vulnerabilities, do we also need a command line option? My vote is currently no, as it adds code complexity with very little added value, we should encourage use of the checked in file.

**Comment by ButterB0wl** [comment]
Yeah only a psychopath would pass in whitelisted vulns by command line every time when a file is available

A use case I could see is adding a vuln to the whitelisted file through the command line and having it persist, maybe through the ossi config menu?

**Comment by ButterB0wl** [comment]
While that use case would be nice to have, i think its introducing a lot of complexity (modifying a file from the command line) for a relatively minor use case.  I don't think anyone will ever complain about this, and if they do they should buy lifecycle anyway.
