### ISSUE TITLE
Decide to add Istanbul for Mocha code coverage or switch to Jest testing framework

### ISSUE THREAD

**Issue by allenhsieh** [sonatype-nexus-community/auditjs#140]
After doing some research we're going to have to decide to switch everything to Jest or to add on Instanbul as a devDep

**Comment by DarthHater** [comment]
I am fine with Instanbul and Mocha to be honest. I don't really know per se what jest would add in comparison? Is it just the newest hot stuff for testing or are there real benefits to adding it?

**Comment by allenhsieh** [comment]
We had a discussion over Slack voice call 2 weeks ago and decided to stick with Istanbul instead of refactoring all the unit tests
