### ISSUE TITLE
Add more helpful output when someone doesn't specify iq/ossi

### ISSUE THREAD

**Issue by ButterB0wl** [sonatype-nexus-community/auditjs#155]
So we get the help message if we specify a flag without iq/ossi: 
![image](https://user-images.githubusercontent.com/37317224/74370376-fe05f500-4da4-11ea-9f94-ff6a617721ad.png)

However if you put a string in without any hyphens:
![image](https://user-images.githubusercontent.com/37317224/74370496-2e4d9380-4da5-11ea-9b0d-3032d55e3491.png)

Just need to add something to handle that case

**Comment by DarthHater** [comment]
Oh wonderful, hah. Easy fix, I can grab this likely.
