### ISSUE TITLE
[FEATURE] Add --bower flag to force use of bower.json file

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/auditjs#178]
User testing exposed a use case where an environment was using both npm and bower. When running `auditjs`, the npm package.json was found and used, but the bower.json was ignored.

There may be valid use cases where the user wants the bower.json file to be used instead (and/or even combined with the npm dependencies?). This could be addressed by adding a `--bower` flag to force use of the bower.json file.

It is acknowledged that bower is basically deprecated, but many projects are still in the process of migrating away from using it.

cc @bhamail / @DarthHater / @allenhsieh / @ken-duck

**Comment by DarthHater** [comment]
I'm wondering if we should just:

- Merge bower AND node_modules
- Output to user "We found Bower and NPM, scanning both"

Command line flag doesn't totally bother me, just thinking about what's the best user experience?
