### ISSUE TITLE
nexus 3.23.0 image from quay.io found some  security vulnerabilities 

### ISSUE THREAD

**Issue by anilsaini1212** [sonatype-nexus-community/auditjs#205]
Hi ,Have a Good Day , we are using the nexus 3.23.0 image from quay.io in our Env
We found some vulnerabilities while scanning the image through Atrifactory X-ray scanner

![nexus-3 23 0](https://user-images.githubusercontent.com/39952553/93451220-8547b800-f8f4-11ea-970c-43ed9493ff34.PNG)

May you please check 

Thanks 
Anil kumar

**Comment by DarthHater** [comment]
@anilsaini1212 this seems unrelated to AuditJS? Those look like dependencies of Nexus Repository itself?

**Comment by DarthHater** [comment]
Closing as this appears unrelated to AuditJS
