### ISSUE TITLE
[BUG] --whitelist parameter is not used, default file used instead

### ISSUE THREAD

**Issue by Lutty76** [sonatype-nexus-community/auditjs#217]
**Describe the bug**
When i set whitelist parameter for specifie a file to be used for ignoring cve, auditjs is still using auditjs.json

**To Reproduce**
1. Run auditjs ossi -qj --whitelist ignore_cve_ui.json with ignored vulnerabilities in file ignore_cve_ui.json
2. See vulnerabilities appear in list
3. cp ignore_cve_ui.json auditjs.json 
4. Run again auditjs ossi -qj --whitelist ignore_cve_ui.json
5. Vulnerabilities not appear in list

**Expected behavior**
Vulnerability should not appear in list with only  ignore_cve_ui.json file

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/9408013/99686020-765fbc00-2a83-11eb-99ca-f944b8267a41.png)

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - NodeJS Version: v12.19.0
 - Version 4.0.20

**Additional context**

**Comment by Lutty76** [comment]
https://github.com/sonatype-nexus-community/auditjs/blob/master/src/Whitelist/VulnerabilityExcluder.ts

Line 22, nothing for taking account the parameter ;)

**Comment by DarthHater** [comment]
@Lutty76 thanks for filing (and @francois-roget for the PR by the looks of it!), I tagged @Slim-Shary to take a gander!
