### ISSUE TITLE
[BUG] Cache location is not used

### ISSUE THREAD

**Issue by calvinbui** [sonatype-nexus-community/auditjs#230]
**Describe the bug**
Cache location is not used when running `ossi` but is when clearing it's cache

**To Reproduce**
Set `CacheLocation` in `.oss-index-config`:

```shell-session
$ cd ~/.ossindex

$ ls -a -1
.
..
.oss-index-config

$ cat .oss-index-config
Username: ''
Token: ''
CacheLocation: /Users/calvin/.ossindex/auditjscache
```

Go into my project and run `npx auditjs@4.0.22 ossi` then look at the `.ossindex` folder again. The `auditjs` is used for caching and has 404 files.

```
$ cd myproject

$ npx auditjs@4.0.22 ossi
...
...

$ cd ~/.ossindex

$ ls -a -1
.
..
.auditjs.combined.log
.oss-index-config
auditjs

$ ls -1 auditjs | wc -l
404
```

I run the clear cache operation and it generates the expected `auditjscache` location

```
$ npx auditjs@4.0.22 ossi --clear
Cache location: /Users/calvin/.ossindex/auditjscache
Cache cleared

$ ls -a -1
.
..
.auditjs.combined.log
.oss-index-config
auditjs
auditjscache

$ ls -1 auditjs | wc -l
404

$ ls -1 auditjscache | wc -l
0
```

**Expected behavior**
The cache location set is used

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15
 - NodeJS Version: 15.3.0
 - Version 4.0.22

**Additional context**
Additionally, is there a way to set a relative path for the auditjs cache? I'd like to keep each cache per repo/project rather than a global cache. This would be beneficial for CI/CD builds.

cc @bhamail / @DarthHater / @allenhsieh / @Slim-Shary

**Comment by DarthHater** [comment]
@calvinbui I imagine this is an easy fix, @Slim-Shary alerted me to it, we will take a look at it as soon as we can! We welcome PRs if you got the time and want to dig in too.
