### ISSUE TITLE
[FEATURE] Sarif format support

### ISSUE THREAD

**Issue by arddluma** [sonatype-nexus-community/auditjs#245]
* **What are you trying to do?**
Integrate auditjs into the pipeline with better way of showing results.
* **What feature or behavior is this required for?**
With the sarif format support output will be shown on the `Security tab` of the repository.
* **How could we solve this issue? (Not knowing is okay!)**
https://docs.oasis-open.org/sarif/sarif/v2.0/sarif-v2.0.html
https://codeql.github.com/docs/codeql-cli/sarif-output/
* **Anything else?**
--
cc @bhamail / @DarthHater / @allenhsieh / @ken-duck

Thank you!

**Comment by DarthHater** [comment]
Hey there! No real objection to this. Want to send us a PR? I'm pretty sure you could do this already using `jq` etc... and consuming the existing json output, but if you want it built into the tool I'd be glad to help out.
