### ISSUE TITLE
Nexus Platform Plugin in Jenkins is not working  for npm auditjs dependencies in the code

### ISSUE THREAD

**Issue by vinishakurapati** [sonatype-nexus-community/auditjs#252]
So  used "**npx auditjs iq -a application id -s build -h [http://grs-sonatype1.companyname.linux:8070] -u username -p passwrd* "commad in cmd and it produces report in  sonatype nexus iq server with correct results of violations.

I need this auditjs step incorporated in such a way that it needs to be scanned using nexus iq platform plugin in jenkins, but this plugin is integrated and works well with other code where there are no auditjs dependencies. The plugin is scanning the code in source repository but generating incorrect( all zeros) result.

In the build log ,it is observed that it does run a scan and generates a link to nexus iq server report but it shows wrong - in my case all zeros for policy violations and other issues, which is a wrong result as the code does show violations when the above mentioned auditjs command is run in command prompt, and manually pointed it to browser generated correct results.

Is there any way to generate such results without running shell command or maybe a way to edit package.json file of the app code? 

**To Reproduce**
Run a freestyle build job using nexus plugin in  jenkins using auditjs dependent code and it generates wrong report.

**Expected behavior**
It should display a "view link" option with correct results alongside a small graphical chart in the jenkins build UI.

cc @bhamail / @DarthHater / @allenhsieh / @Slim-Shary

**Comment by bhamail** [comment]
@vinishakurapati Auditjs and the Nexus plugin are not related at all. They are separate tools.

**Comment by bhamail** [comment]
Closing, as Nexus Platform Plugin is not intended to show auditjs output.
