### ISSUE TITLE
[BUG] Sonatype Service Temporarily Unavailable

### ISSUE THREAD

**Issue by shamin** [sonatype-nexus-community/auditjs#267]
**Describe the bug**
Getting an error saying that Service Temporarily Unavailable 

**To Reproduce**
1. Run `auditjs ossi -q`
2. See error
```
[2023-03-17T14:35:08.980] [ERROR] auditjs - There was an error auditing with Sonatype OSS Index Error: There was an error making the request: Error: Service Temporarily Unavailable
    at .../node_modules/auditjs/bin/Services/OssIndexRequestService.js:71:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
```

**Desktop (please complete the following information):**
 - OS: Mac OS
 - NodeJS Version: 16.17.0
 - Version: 4.0.39

**Additional context**
- The problem stated showing up from today morning, it is not working even with the credentials.
- Also checked the service link mentioned in the docs (https://ossindex.sonatype.org/). 
   This is giving and error `503 Service Temporarily Unavailable` 

cc @bhamail / @DarthHater / @allenhsieh / @Slim-Shary

**Comment by danny-lowery** [comment]
I'm seeing the same error; as a result, all our nightly audit pipelines are failing.

**Comment by danny-lowery** [comment]
The 503 error is no longer occurring so the issue has been resolved now👍

**Comment by shamin** [comment]
Thanks @danny-lowery. It is resolved now.
