### ISSUE TITLE
Adding support for scanning CDNs (cdnjs and jsdelivr)

### ISSUE THREAD

**Issue by stephengroat** [sonatype-nexus-community/auditjs#28]
Just an idea, but figuring out a way to add support for scanning sets of files for `script` tags, looking at the targets, and pulling package information and versions from those.

for `jsdelivr`, it's super easy since it acts as a `npm` CDN.

`cdnjs` is a little bit harder, but more popular (so i think important to include). I was thinking of using the [CDNJS API](https://cdnjs.com/api) to get the repository associated with the package, but i'm not sure how to connect the git repo with the npm package name yet

**Comment by OSSIndex-Admin** [comment]
Definitely an interesting idea. Thanks! I don't know anything about jsdelivr or cdnjs yet, but will make some time to try them out and see if your idea could be added. I like it.

**Comment by ajurgenson55** [comment]
Closing, if this is still a need reopen a new issue
