### ISSUE TITLE
Whitelisted vulnerabilities should be marked as "skipped" in JUnit report

### ISSUE THREAD

**Issue by thiagofigueiro** [sonatype-nexus-community/auditjs#36]
## Description

When running `auditjs -w file.json`, the application correctly exits with status 0 if it encounters vulnerabilities present in the whitelist file.

The JUnit report doesn't follow the same logic and marks whitelisted vulnerabilities as failures.

## Example

When file.json contains:
```json
[
    8402848607
]
```

And I run `auditjs -r -w file.json` against a project containing a vulnerable version of `brace-expansion`, the resulting report contains:

```xml
<?xml version="1.0" encoding="UTF-8"?>
  <testsuite name="auditjs.security.scan_node_modules" errors="0" tests="482" package="test" id="" skipped="0" failures="1">
<!-- passing test case entries ...  -->
    <testcase name="brace-expansion">
      <failure message="Found 1 vulnerabilities. See stacktrace for details.">Details:

                        [
  {
    "id": 8402848607,
    "title": "Regular Expression Denial of Service (ReDoS)",
    "description": "> brace expansion versions before 1.1.7 are vulnerable to Regular Expression Denial of Service attacks.\n> \n> -- [nodesecurity.io](https://nodesecurity.io/advisories/338)",
    "versions": [
      "&lt;=1.1.6"
    ],
    "references": [
      "https://github.com/juliangruber/brace-expansion/issues/33",
      "https://github.com/juliangruber/brace-expansion/pull/35",
      "https://github.com/juliangruber/brace-expansion/pull/35/commits/b13381281cead487cbdbfd6a69fb097ea5e456c3",
      "https://nodesecurity.io/advisories/338"
    ],
    "published": 1493204922978,
    "updated": 1494211989170,
    "depPaths": [
      "/gulp-minify/gulp-util/through2/uglify-es/minimatch/brace-expansion"
    ]
  }
]
      </failure>
    </testcase>
```

## Expected result

The expected result would be a JUnit report that marks whitelisted issues as "skipped". Using the example above, the expected result would be:

```xml
<?xml version="1.0" encoding="UTF-8"?>
  <testsuite name="auditjs.security.scan_node_modules" errors="0" tests="482" package="test" id="" skipped="1" failures="0">
<!-- passing test case entries ...  -->
    <testcase name="brace-expansion">
      <skipped message="8402848607 is in the whitelist"/>
    </testcase>
```

Changes:
1. The testsuite attribute counts change from `skipped="0" failures="1"` to `skipped="1" failures="0"`
2. The testcase element contains a `<skipped>` element rather than `<failure>`.

**Comment by thiagofigueiro** [comment]
Upon further investigation, I believe this issue is - at least in part - caused by the simplified whitelist format.

https://github.com/OSSIndex/auditjs/blob/7b14b2203e100715aec3aaf6ccced0d606184a24/audit.js#L369-L378


In the simplified format, the `prepareWhitelist` function incorrectly assumes `whitelist` is an array of hashes (line 376).

**Comment by OSSIndex-Admin** [comment]
Thank you for the very descriptive report.

I am looking at the issues now. It looks like there is some broken logic in the counts which needs repairing. I am resolving this first, I will then look to the "skipped" testcase element.

**Comment by OSSIndex-Admin** [comment]
I think the counts should be right now. The testcase element will take a little longer.

**Comment by ajurgenson55** [comment]
We opened a new issue to re-implement junit testing and if/when we prioritize it, we will make sure whitelisted items are skipped
