### ISSUE TITLE
chocolatey: is misleading on macOS

### ISSUE THREAD

**Issue by DanielRuf** [sonatype-nexus-community/auditjs#52]
We use homebrew and nodenv to set the Node.js version in projects.

But chocolatey is a bit misleading in this case.

https://github.com/OSSIndex/auditjs/blob/8736d38e5014ebf5d2f282c7e73b582d1159c25c/audit.js#L135

Is there a reason to use `chocolatey:` for all clients and platforms?

**Comment by ken-duck** [comment]
Heh. I agree that is rather confusing, and I had completely forgot this was in there :D

OSS Index does not currently have filtering by operating system, which means that we report the same vulnerabilities for "nodejs" regardless of operating system at this time.

OSS Index does not provide vulnerabilities for "homebrew" at this time, so the best way to report nodejs vulnerabilities is just to select one of the known good package systems and use that. If OSS Index *did* have homebrew package knowledge, it would report the exact same set of vulnerabilities.

So choosing "chocolatey" does not really change the data that we would report, though I admit it is rather confusing. I would love to support homebrew sometime in the future here, at which point it would make sense to detect the OS and request the vulnerabilities for the appropriate system, if for no other reason for it not to be misleading.

I hope that explanation makes sense.

**Comment by ajurgenson55** [comment]
This should not be an issue with the current read-installed refactor
