### ISSUE TITLE
not all releases on https://github.com/OSSIndex/auditjs/releases

### ISSUE THREAD

**Issue by DanielRuf** [sonatype-nexus-community/auditjs#63]
It seems some are not properly tagged.

**Comment by ken-duck** [comment]
Indeed, you are quite right. I do not have this automated yet and have missed some. I will endeavour to ensure things are synced up better in the future, and given a chance will go back in time and catch things up.

Meanwhile I will have to let this issue linger for a while as a reminder.

**Comment by ajurgenson55** [comment]
We have implemented semver auto releases to npmjs with circleci
