### ISSUE TITLE
check libnpm as npm replacement

### ISSUE THREAD

**Issue by DanielRuf** [sonatype-nexus-community/auditjs#66]
`libnpm` seems to provide many parts of the npm API without the need to use the full npm.

Could this be used instead of `npm`?
I'm not yet sure.

https://www.npmjs.com/package/libnpm

**Comment by DarthHater** [comment]
@DanielRuf are you talking about for when we resolve dependencies? @ajurgenson55 @allenhsieh and I took a bit of a different path with AuditJS 4.0.0, we are using `read-installed` which is the lib npm uses to resolve what has been installed. You can see this on the `alpha` branch.

**Comment by DanielRuf** [comment]
Exactly. I would have to take a look again to give some more feedback.

**Comment by DarthHater** [comment]
Word up! Take a gander at our branch. I have https://github.com/sonatype-nexus-community/auditjs/tree/FixReadInstalled where I got it working as I wanted it to. This got us around having to use the npm cli stuff, and it's the lib that the npm founder wrote to actually resolve stuff, so it feels right! Would love feedback.

**Comment by ajurgenson55** [comment]
Closing for now, check it out and see if it works for you.  feel free to reopen a new issue if you find something specific with how we use read-installed to determine the dependencies.
