### ISSUE TITLE
PnP (Yarn) support

### ISSUE THREAD

**Issue by DanielRuf** [sonatype-nexus-community/auditjs#70]
There is the new Plug'n'Play concept which makes node_modules obsolete:

https://github.com/yarnpkg/rfcs/pull/101

https://github.com/yarnpkg/yarn/pull/6382

https://www.reddit.com/r/node/comments/9fh89w/yarn_plugnplay_getting_rid_of_node_modules/

**Comment by DanielRuf** [comment]
So it might make sense to define the directory to check or some mapping (like the new pnp file).

**Comment by ken-duck** [comment]
Heavy. Thanks for the heads up. I'll look into exploring these various options. It will have to wait a little while as I am currently mostly focussed on getting the other OSS clients upgraded (for other languages/ecosystems).
Once I have them upgraded I will be able to revisit the npm client and ensure it works for these alternatives.

**Comment by DanielRuf** [comment]
For npm, see https://github.com/npm/tink which is a different implementation.

**Comment by ken-duck** [comment]
Whoa, this one has lingered. Sorry for that. I am looking into implementing a lock file check, which I suspect is one way to deal with this problem. Once that is done I will dig further to see if there are more alternatives that make sense.

**Comment by ken-duck** [comment]
Release 3.1.1 is out, with support for the yarn.lock file:

```
auditjs -p yarn.lock
```

**Comment by DarthHater** [comment]
I believe this can be closed, and we have yarn support in 4.0.x (see #125 as feedback there would be very useful!)
