### ISSUE TITLE
Support for json output

### ISSUE THREAD

**Issue by rrupesh** [sonatype-nexus-community/auditjs#81]
Looked at the documentation. I couldn't find a way to generate json output from auditjs run. Kindly consider adding json output support.

**Comment by ken-duck** [comment]
I think this is a good idea. I much prefer JSON myself. Do you have a suggestion for a format? Not sure if there is a common format that folks expect for this sort of thing. I can invent my own, but may as well have an ask first (and I will look around a bit as well).

Meanwhile a workaround could be using this module against our XML output (or something similar): https://www.npmjs.com/package/xml-to-json-stream

**Comment by DarthHater** [comment]
@rrupesh I've got a WIP branch of something that does this, go ahead and check it out at #96 . 

Not the most clear build local steps yet in the README but:

```
npm i
npm run build
npm run start -- ossi --json
```

That should test the app at least locally on itself, and give you an idea of how it outputs.

If you want to do this in a different directory (test your own app):

`node /path/to/auditjs/bin/index.js ossi --json`

Would love to know your feedback!

**Comment by DarthHater** [comment]
Going to close this for now, feel free to reopen if it doesn't meet your needs, would love to have the conversation!
