### ISSUE TITLE
Add User-Agent for requests to OSSI

### ISSUE THREAD

**Issue by jdillon** [sonatype-nexus-community/auditjs#82]
Please update the HTTP request to OSSI to include a reasonable User-Agent for audit.js.

**Comment by DarthHater** [comment]
Hi there @jdillon , in the `alpha` branch of the auditjs 4.0.0 stuff, I've crafted this up for a User Agent:

```
  public static getUserAgent(): string[] {
    let nodeVersion = process.versions;
    let environment = 'NodeJS';
    let environmentVersion = nodeVersion.node;
    let system = `${os.type()} ${os.release()}`;

    return ['User-Agent', `AuditJS/${pack.version} (${environment} ${environmentVersion}; ${system})`];
  }
```

It'll drag in the AuditJS version, and then a lil bit of info on node and the system. That ok by you?

**Comment by DarthHater** [comment]
We've done this work, and I believe it's fine. Going to close this issue for now (reopen if you'd like @jdillon )
